In [1]:
import tensorflow as tf

In [2]:
a = tf.reshape(tf.range(9), [3, 3])

In [3]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [4]:
tf.pad(a, [[0, 0], [0, 0]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [5]:
# 填充
# tf.pad(tensor, [[维度一的填充], [维度二的填充], .....])
tf.pad(a, [[1, 0], [0, 0]])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [6]:
# 在行维度的上下填充一行
tf.pad(a, [[1,1], [0,0]])

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]], dtype=int32)>

In [7]:
tf.pad(a, [[1,1], [1,0]])

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 1, 2],
       [0, 3, 4, 5],
       [0, 6, 7, 8],
       [0, 0, 0, 0]], dtype=int32)>

In [8]:
tf.pad(a, [[1,1],[1,1]])

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [9]:
# image padding
a = tf.random.normal([4, 28, 28, 3])

In [10]:
# [batch,raw,colum,channel]
b = tf.pad(a, [[0,0],[2,2],[2,2],[0,0]])

In [11]:
b.shape

TensorShape([4, 32, 32, 3])

In [12]:
a = tf.reshape(tf.range(9), [3, 3])

In [13]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [14]:
# tile 复制, 不同与broadcast的假copy,tile会真copy
# [第一个维度变为原来的1倍, 第二个维度变为原来的2倍]
tf.tile(a, [1, 2])

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]], dtype=int32)>

In [15]:
# tile VS broadcast_to
# expand_dims增加维度
aa = tf.expand_dims(a, axis=0)

In [16]:
aa

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]], dtype=int32)>

In [17]:
# 第一个维度复制一次,其他维度不动
tf.tile(aa, [2, 1, 1])

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]], dtype=int32)>

In [18]:
# 将维度broadcast为[2, 3, 3]
tf.broadcast_to(aa, [2, 3, 3])

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]], dtype=int32)>