In [2]:
import tensorflow as tf

In [3]:
a = tf.ones([1,5,5,3])

In [4]:
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [6]:
a[0][0][0][2] #scalar

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [7]:
a = tf.random.normal([4,28,28,3])

In [8]:
a[1].shape

TensorShape([28, 28, 3])

In [9]:
a[1,2].shape

TensorShape([28, 3])

In [10]:
a[1,2,3].shape

TensorShape([3])

In [11]:
a[1,2,3,2].shape

TensorShape([])

In [12]:
a = tf.range(10)

In [13]:
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [14]:
a[-1:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [15]:
a[-2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9], dtype=int32)>

In [16]:
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [17]:
a[:-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [19]:
a = tf.ones([4,28,28,3])

In [20]:
a.shape

TensorShape([4, 28, 28, 3])

In [21]:
a[0].shape

TensorShape([28, 28, 3])

In [22]:
a[0,:,:,:].shape

TensorShape([28, 28, 3])

In [23]:
a[0,1,:,:].shape

TensorShape([28, 3])

In [24]:
a[:,:,:,0].shape

TensorShape([4, 28, 28])

In [25]:
a[:,:,:,2].shape

TensorShape([4, 28, 28])

In [26]:
a[:,0,:,:].shape

TensorShape([4, 28, 3])

In [27]:
a = tf.range(4)

In [28]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [29]:
a[::-1] # 逆序

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0], dtype=int32)>

In [30]:
a[::-2] # 从右向左step等于2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [31]:
a[2::-2] # [2,1,0]取step为2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>

In [33]:
a = tf.ones([4,28,28,3])

In [34]:
a.shape

TensorShape([4, 28, 28, 3])

In [35]:
a[0:2,:,:,:].shape

TensorShape([2, 28, 28, 3])

In [36]:
a[:,0:28:2,0:28:2,:].shape

TensorShape([4, 14, 14, 3])

In [37]:
a[:,:14,:14,:].shape

TensorShape([4, 14, 14, 3])

In [39]:
a[:,14:,14:,:].shape

TensorShape([4, 14, 14, 3])

In [40]:
a[:,::2,::2,:].shape

TensorShape([4, 14, 14, 3])

In [41]:
a = tf.random.normal([2,4,28,28,3])

In [42]:
a[0].shape

TensorShape([4, 28, 28, 3])

In [43]:
a[0,:,:,:,:].shape

TensorShape([4, 28, 28, 3])

In [44]:
# ...代表推算的多个维度全取
a[...,0].shape

TensorShape([2, 4, 28, 28])

In [46]:
a[0,...].shape

TensorShape([4, 28, 28, 3])

In [47]:
a[0,...,2].shape

TensorShape([4, 28, 28])

In [48]:
a[1,0,...,0].shape

TensorShape([28, 28])

In [49]:
"""
data:[classes,students,subjects]
     [ 4,  35 , 8]
"""

'\ndata:[classes,students,subjects]\n     [ 4,  35 , 8]\n'

In [51]:
a = tf.ones([4,35,8])

In [52]:
# tf.gather
# 在a的第一个维度取索引为2,3的data
tf.gather(a,axis=0,indices=[2,3]).shape

TensorShape([2, 35, 8])

In [55]:
# 在a的第一个维度按顺序取列表中[2,1,4,0]索引
tf.gather(a,axis=0,indices=[2,1,3,0]).shape

TensorShape([4, 35, 8])

In [56]:
# 在第二个维度
tf.gather(a,axis=1,indices=[2,3,7,9,16]).shape

TensorShape([4, 5, 8])

In [57]:
# 第三个维度
tf.gather(a,axis=2,indices=[2,3,7]).shape

TensorShape([4, 35, 3])

In [59]:
# tf.gather_nd
# data: [classes, students, subjects]
a.shape

TensorShape([4, 35, 8])

In [60]:
# 取第一个班级的所有人的所有成绩
tf.gather_nd(a,[0]).shape

TensorShape([35, 8])

In [61]:
# 取第一个班级,第二个人的所有成绩
tf.gather_nd(a,[0,1]).shape

TensorShape([8])

In [62]:
# 取第一个班级,第二个人的第三科成绩
tf.gather_nd(a,[0,1,2]).shape

TensorShape([])

In [63]:
tf.gather_nd(a,[[0,1,2]]).shape

TensorShape([1])

In [64]:
# 取第一个班级的第一个人的所有成绩,取第二个班级的第二个人的所有成绩,取第三个班级的第三个人的所有成绩
tf.gather_nd(a,[[0,0],[1,1],[2,2]]).shape

TensorShape([3, 8])

In [65]:
# 取第一个班级的第一个人的第一科成绩,取第二个班级的第二个人的第二科成绩,取第三个班级的第三个人的第三科成绩
tf.gather_nd(a,[[0,0,0],[1,1,1],[2,2,2]]).shape

TensorShape([3])

In [67]:
tf.gather_nd(a,[[[0,0,0],[1,1,1],[2,2,2]]]).shape

TensorShape([1, 3])

In [68]:
# tf.boolean_mask
a = tf.ones([4,28,28,3])

In [69]:
# 取第一张照片和第二张照片
tf.boolean_mask(a,mask=[True,True,False,False]).shape

TensorShape([2, 28, 28, 3])

In [70]:
# 取所有图片的RG颜色通道
tf.boolean_mask(a,mask=[True,True,False],axis=3).shape

TensorShape([4, 28, 28, 2])

In [71]:
a=tf.ones([2,3,4])

In [72]:
# 对第二个维度的所有数据进行操作
tf.boolean_mask(a,mask=[[True,False,False],[False,True,True]])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>