In [61]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [3]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [4]:
tf.convert_to_tensor([1,2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
tf.convert_to_tensor([[1],[2.]])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [8]:
tf.zeros([]) # scalar

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [9]:
tf.zeros([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [10]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
tf.zeros([2,3,3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [12]:
tf.ones(1) # vector

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [13]:
tf.ones([])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [14]:
tf.ones([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [15]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
a = [[2,3],[4,5]]

In [18]:
tf.ones_like(a) # 创建一个维度和shape跟a的相同的

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [20]:
tf.fill([6,6],8.)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8.]], dtype=float32)>

In [22]:
# 正态分布(设置均值为1,方差为1)上随机采样
tf.random.normal([2,2],mean=1,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.6105145 , 0.89623594],
       [0.68276215, 1.2319583 ]], dtype=float32)>

In [23]:
# 默认为mean=0,stddev=1
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.30912694, -0.19565323],
       [ 0.3833975 ,  0.07019342]], dtype=float32)>

In [25]:
# 截断正态分布
tf.random.truncated_normal([2,2],mean=0,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.49787155, -0.43577027],
       [ 0.24545772, -0.6364073 ]], dtype=float32)>

In [26]:
# 均匀分布上随机采样
tf.random.uniform([2,2],minval=0,maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2363323 , 0.4111848 ],
       [0.21142137, 0.38590634]], dtype=float32)>

In [27]:
tf.random.uniform([2,2],minval=0,maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[56.863712, 75.450096],
       [50.967182, 70.085815]], dtype=float32)>

In [28]:
idx = tf.range(10)
# 随机打散
idx = tf.random.shuffle(idx)

In [29]:
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 0, 9, 7, 1, 8, 5, 3, 2, 4], dtype=int32)>

In [40]:
# 10张照片
a = tf.random.normal([10,784])
b = tf.random.uniform([10],maxval=10,dtype=tf.int32)

In [41]:
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[ 1.5184534 ,  0.9039594 ,  1.2074845 , ...,  1.119006  ,
         0.06882787, -0.32101518],
       [-0.78811526,  1.3663292 , -1.6545601 , ...,  0.23034438,
        -1.2214478 ,  0.06727121],
       [ 0.23328601, -0.45618972, -0.52999   , ..., -0.44081146,
         1.7280146 , -0.40337685],
       ...,
       [ 0.05728425, -0.2411322 , -1.6886231 , ...,  0.42791805,
         0.48714158, -0.18872994],
       [ 1.0287937 , -1.0696169 , -0.56982225, ...,  0.32561976,
        -0.47099748, -0.69567573],
       [-0.566353  ,  0.85462207, -1.7966139 , ...,  0.35330534,
        -1.0431174 , -1.682859  ]], dtype=float32)>

In [42]:
# 按照idx的索引取值,重新排列a,b
a = tf.gather(a,idx)
b = tf.gather(b,idx)

In [43]:
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[ 0.4973088 ,  1.0760757 , -0.7186667 , ..., -0.35385886,
        -0.5644542 ,  0.8696509 ],
       [ 1.5184534 ,  0.9039594 ,  1.2074845 , ...,  1.119006  ,
         0.06882787, -0.32101518],
       [-0.566353  ,  0.85462207, -1.7966139 , ...,  0.35330534,
        -1.0431174 , -1.682859  ],
       ...,
       [ 0.23130147,  1.0455946 , -0.61420673, ..., -0.54340076,
        -1.6090993 ,  1.2095499 ],
       [ 0.23328601, -0.45618972, -0.52999   , ..., -0.44081146,
         1.7280146 , -0.40337685],
       [ 0.11369618, -0.77096844, -0.3923473 , ..., -0.15197757,
        -0.58546805, -0.58546984]], dtype=float32)>

In [44]:
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 8, 3, 3, 4, 3, 7, 7, 0, 8], dtype=int32)>

In [45]:
tf.constant(1) # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [46]:
tf.constant([1]) # vector/tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [48]:
tf.constant([[1,2.],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [50]:
# 模拟4张照片的label
out = tf.random.uniform([4,10])
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0.32103574, 0.1332438 , 0.00559521, 0.17963552, 0.71421885,
        0.7564701 , 0.80816364, 0.980039  , 0.6708164 , 0.5151917 ],
       [0.93058264, 0.35696805, 0.6352519 , 0.5515181 , 0.09365427,
        0.70741904, 0.40041256, 0.99556315, 0.2815225 , 0.4143027 ],
       [0.5493549 , 0.33827555, 0.28284562, 0.76382446, 0.2748736 ,
        0.48603737, 0.6188024 , 0.73279667, 0.27569354, 0.46018076],
       [0.22016847, 0.5616708 , 0.6042646 , 0.8950442 , 0.70531106,
        0.12966907, 0.3922466 , 0.20211303, 0.4845351 , 0.51859426]],
      dtype=float32)>

In [51]:
y = tf.range(4)

In [52]:
# [0,1,2,3] => [[1,0,0,0,0,..],[0,1,0,0,..],[0,0,1,0,..],[0,0,0,1,0,..]]
y = tf.one_hot(y,depth=10)

In [54]:
# 计算loss
# mse()均方误差函数,计算出每一个样本的均方误差
loss = tf.keras.losses.mse(y,out)

In [55]:
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.3922424 , 0.3898782 , 0.30334276, 0.19527988], dtype=float32)>

In [57]:
# 求出所有样本mse的平均值
loss = tf.reduce_mean(loss)

In [58]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.32018578>

In [96]:
# 设置第一层的输出神经元个数为10个=>10
net = layers.Dense(10)

In [97]:
# 升维 8 => 10 
# 4个样本,input_dim..=8
# [b,]
net.build((4,8))

In [98]:
# w | w:[input_dim,output_dim]
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.53284013,  0.05516887, -0.02065784,  0.3403821 , -0.54616517,
        -0.47538775, -0.03137797, -0.09422764,  0.40767896,  0.53407407],
       [-0.49301893, -0.17677504, -0.10031235,  0.2506591 ,  0.19297493,
        -0.11981007,  0.02448785, -0.5363359 , -0.28633246, -0.5581502 ],
       [-0.23305517, -0.20434874, -0.17455927,  0.38995272, -0.3727923 ,
        -0.02182239,  0.03024   , -0.4162954 ,  0.17265153,  0.29909295],
       [ 0.01360184,  0.14581704,  0.46975505,  0.49607038, -0.43022677,
        -0.15132391, -0.4635974 , -0.5251991 ,  0.15270853, -0.00811768],
       [-0.38400024,  0.36294377,  0.22626567, -0.2425429 , -0.05847871,
         0.47094345,  0.5031835 , -0.49241516,  0.4917307 ,  0.5060817 ],
       [ 0.36051548,  0.26478755, -0.14095342, -0.14212137, -0.53184587,
        -0.13823879, -0.26536462,  0.15348268,  0.10395849,  0.49242413],
       [-0.22408885, -0.15871328, -0.01134491,  0.02373433

In [89]:
# b
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [99]:
# [b,28*28]
x = tf.random.normal([4,784])

In [101]:
x.shape

TensorShape([4, 784])

In [102]:
# output_dim=10
net = layers.Dense(10)
net.build((4,784))

In [106]:
net(x).shape

TensorShape([4, 10])

In [108]:
# w
net.kernel.shape

TensorShape([784, 10])

In [110]:
net.bias.shape

TensorShape([10])

In [111]:
# (b,32,32,channel)
x = tf.random.normal((4,32,32,3))

In [115]:
# 卷积层后[4,32,32,16]
net = layers.Conv2D(16,kernel_size=3)

In [117]:
net(x).shape

TensorShape([4, 30, 30, 16])