In [1]:
import tensorflow as tf

In [2]:
# Broadcasting优化手段,起始并没有复制数据
x = tf.random.normal([4,32,32,3])

In [3]:
(x + tf.random.normal([3])).shape

TensorShape([4, 32, 32, 3])

In [4]:
(x + tf.random.normal([32,32,1])).shape

TensorShape([4, 32, 32, 3])

In [5]:
(x + tf.random.normal([4,1,1,1])).shape

TensorShape([4, 32, 32, 3])

In [6]:
# 不能扩张
(x + tf.random.normal([1,4,1,1])).shape

InvalidArgumentError: Incompatible shapes: [4,32,32,3] vs. [1,4,1,1] [Op:AddV2]

In [7]:
x.shape

TensorShape([4, 32, 32, 3])

In [8]:
(x + tf.random.normal([4,1,1,1])).shape

TensorShape([4, 32, 32, 3])

In [10]:
b = tf.broadcast_to(tf.random.normal([4,1,1,1]),[4,32,32,3])

In [12]:
b.shape

TensorShape([4, 32, 32, 3])

In [13]:
# tile真正的copy了数据
a = tf.ones([3,4])

In [14]:
a1 = tf.broadcast_to(a,[2,3,4])

In [15]:
a1

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [16]:
a2 = tf.expand_dims(a,axis=0)

In [18]:
a2.shape

TensorShape([1, 3, 4])

In [19]:
a2 = tf.tile(a2,[2,1,1])

In [20]:
a2

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>