In [1]:
import tensorflow as tf

In [2]:
a = tf.random.shuffle(tf.range(5))

In [3]:
# 逆序
tf.sort(a, direction='DESCENDING')

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [4]:
# 对应原来序列的索引
tf.argsort(a, direction='DESCENDING')

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 2, 1, 3, 0], dtype=int32)>

In [5]:
idx = tf.argsort(a, direction='DESCENDING')

In [6]:
tf.gather(a, idx)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [14]:
# 均匀分布
a = tf.random.uniform([3,3], maxval=10, dtype=tf.int32)

In [15]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 0],
       [8, 4, 3],
       [0, 1, 4]], dtype=int32)>

In [16]:
# 默认在最低维排序
tf.sort(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 2],
       [3, 4, 8],
       [0, 1, 4]], dtype=int32)>

In [17]:
tf.sort(a, direction='DESCENDING')

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 0, 0],
       [8, 4, 3],
       [4, 1, 0]], dtype=int32)>

In [18]:
idx = tf.argsort(a)

In [19]:
idx

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [2, 1, 0],
       [0, 1, 2]], dtype=int32)>

In [20]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 0],
       [8, 4, 3],
       [0, 1, 4]], dtype=int32)>

In [21]:
# 取最后一个维度两个最大的
res = tf.math.top_k(a, 2)

In [23]:
# 索引
res.indices

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [2, 1]], dtype=int32)>

In [24]:
# 值
res.values

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [8, 4],
       [4, 1]], dtype=int32)>

In [25]:
prob = tf.constant([[0.1, 0.2, 0.7],[0.2, 0.7, 0.1]])

In [26]:
target = tf.constant([2, 0])

In [27]:
# 取最大的三个数的索引
k_b = tf.math.top_k(prob, 3).indices

In [28]:
# 转置
k_b = tf.transpose(k_b, [1, 0])

In [29]:
k_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 0],
       [0, 2]], dtype=int32)>

In [32]:
# 升维
target = tf.broadcast_to(target, [3,2])

In [33]:
target

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [2, 0],
       [2, 0]], dtype=int32)>

In [37]:
def accuracy(output, target, topk=(1,)):
    # 最大topk
    maxk = max(topk)
    # batck_size
    batch_size = target.shape[0]
    # 求出最大topk对应的索引,此处当做label
    pred = tf.math.top_k(output, maxk).indices
    # 转置
    pred = tf.transpose(pred, perm=[1, 0])
    # 升维
    target_ = tf.broadcast_to(target, pred.shape)
    # 正确的返回True
    correct = tf.equal(pred, target_)
    
    res = []
    # 遍历topk
    for k in topk:
        # cast数据类型转换,True->1.0,取钱topk
        correct_k = tf.cast(tf.reshape(correct[:k],[-1]), dtype=tf.float32)
        # 求总的正确的个数
        correct_k = tf.reduce_sum(correct_k)
        # 此topk对应的正确率
        acc = float(correct / batch_size)
        # 追加
        res.append(acc)
    
    return res

In [39]:
tf.reshape([[2,3],[3,2],[3,3]],[2,-1])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [2, 3, 3]], dtype=int32)>

In [40]:
tf.reshape([[2,3],[3,2],[3,3]],[-1])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 3, 2, 3, 3], dtype=int32)>

In [41]:
pred = tf.constant([[2,3],[3,2],[3,3]])
tf.transpose(pred, perm=[1, 0])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 3],
       [3, 2, 3]], dtype=int32)>