In [1]:
import tensorflow as tf

In [9]:
# clip_by_value

a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
# 比2大的数就是数本身,比2小的转成2
tf.maximum(a, 2)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [4]:
# 比8小的数就是数本身,比8大的转成8
tf.minimum(a, 8)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 8], dtype=int32)>

In [5]:
tf.clip_by_value(a, 2, 8)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8], dtype=int32)>

In [10]:
a = a-5
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4], dtype=int32)>

In [11]:
tf.nn.relu(a)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4], dtype=int32)>

In [12]:
tf.maximum(a, 0)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4], dtype=int32)>

In [14]:
# clip_by_norm
a = tf.random.normal([2, 2], mean=10)
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.490307,  9.713208],
       [10.631199,  8.26157 ]], dtype=float32)>

In [15]:
# 2范数,即根号下平方和
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=19.122978>

In [26]:
# 这里的clip_by_norm是指对梯度进行裁剪，通过控制梯度的最大范式，防止梯度爆炸的问题，是一种比较常用的梯度规约的方式。
# tf.clip_by_norm 不改变梯度的方向,只是对梯度进行归一化
# 限制vect-- a的模最大为15 , 这里的模即2范数
# 相当于 15 * (ai / tf.norm(a))
# 等比例放缩
aa = tf.clip_by_norm(a, 15)

In [27]:
aa

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.4441648, 7.6190076],
       [8.339077 , 6.480348 ]], dtype=float32)>

In [18]:
# 模
tf.norm(aa)

<tf.Tensor: shape=(), dtype=float32, numpy=14.999999>

In [21]:
(9.490307/19.122978)*15

7.444165077217575

In [28]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.490307,  9.713208],
       [10.631199,  8.26157 ]], dtype=float32)>

In [34]:
b = tf.random.normal([2, 2], mean=200)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[199.15695, 200.69623],
       [200.82016, 198.36736]], dtype=float32)>

In [36]:
# clip_by_global_norm对多个参数整体进行缩放
# 使各个参数的norm加起来不大于指定值
new_grad,total_normal = tf.clip_by_global_norm([a, b], 20)

In [40]:
a, b = new_grad

In [42]:
a, b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.47453535, 0.4856809 ],
        [0.53158236, 0.41309592]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9.958267, 10.035234],
        [10.041431,  9.918786]], dtype=float32)>)

In [41]:
tf.norm(a) + tf.norm(b)

<tf.Tensor: shape=(), dtype=float32, numpy=20.93332>