In [2]:
import tensorflow as tf

In [4]:
# tf.norm(平方求和开根号)
a = tf.ones([3, 5])
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.8729835>

In [6]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: shape=(), dtype=float32, numpy=3.8729835>

In [7]:
b = tf.ones([4,28,28,3])

In [8]:
tf.norm(b)

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

In [9]:
tf.sqrt(tf.reduce_sum(tf.square(b)))

<tf.Tensor: shape=(), dtype=float32, numpy=96.99484>

In [11]:
a.shape

TensorShape([3, 5])

In [12]:
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.8729835>

In [13]:
# ord 1 代表算法: 绝对值后求和
# ord 2 代表算法: 平方求和开根号

# 对索引 1 对应的维度---对每一行的所有列元素平方求和开根号
tf.norm(a,ord=2,axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.236068, 2.236068, 2.236068], dtype=float32)>

In [17]:
tf.norm(a, ord=1)

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [18]:
tf.norm(a, ord=1, axis=0)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([3., 3., 3., 3., 3.], dtype=float32)>

In [19]:
tf.norm(a, ord=1, axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 5., 5.], dtype=float32)>

In [20]:
# reduce_min/max/mean
a = tf.random.normal([4, 10])

In [21]:
tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a)

(<tf.Tensor: shape=(), dtype=float32, numpy=-2.8232973>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.406225>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.10515042>)

In [22]:
tf.reduce_min(a, axis=1), tf.reduce_max(a, axis=1), tf.reduce_mean(a, axis=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.4137138 , -0.97382516, -0.8651816 , -2.8232973 ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.406225 , 2.2046094, 1.2966218, 1.7491497], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.14122127,  0.4827407 , -0.02416773, -0.17919257], dtype=float32)>)

In [23]:
# argmax/argmin 返回索引
a.shape

TensorShape([4, 10])

In [24]:
tf.argmax(a).shape

TensorShape([10])

In [25]:
# 默认axis=0
tf.argmax(a)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 0, 1, 3, 1, 0, 1, 2, 0, 1])>

In [26]:
tf.argmax(a, axis=0)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 0, 1, 3, 1, 0, 1, 2, 0, 1])>

In [27]:
tf.argmax(a, axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 6, 0, 6])>

In [28]:
a = tf.constant([1,3,2,1,4])

In [29]:
b = tf.range(5)

In [32]:
# 判断对应位置是否相等
tf.equal(a, b)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False,  True, False,  True])>

In [33]:
res = tf.equal(a, b)

In [35]:
# cast类型转换,True->1,False->0
tf.reduce_sum(tf.cast(res, dtype=tf.int32))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 0, 1], dtype=int32)>

In [36]:
a = tf.constant([[0.1, 0.2, 0.7], [0.9, 0.05, 0.05]])

In [37]:
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.1 , 0.2 , 0.7 ],
       [0.9 , 0.05, 0.05]], dtype=float32)>

In [39]:
# 求最大的位置的索引
pred = tf.cast(tf.argmax(a, axis=1), dtype=tf.int32)
pred

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>

In [40]:
y = tf.constant([2, 1])
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

In [41]:
tf.equal(y, pred)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [42]:
# 求为True的数量(将True转换为1求和)
correct = tf.reduce_sum(tf.cast(tf.equal(y, pred), dtype=tf.int32))

In [43]:
correct

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [44]:
correct/2

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [45]:
a = tf.range(5)

In [46]:
# tf.unique
tf.unique(a)

Unique(y=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>)

In [49]:
a = tf.constant([4, 2, 2, 4, 3])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 2, 2, 4, 3], dtype=int32)>

In [50]:
# [4, 2, 2, 4, 3] --> [4, 2, 3] --> [0, 1, 1, 0, 2] 对应第二个索引
tf.unique(a)

Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2], dtype=int32)>)