In [23]:
import tensorflow as tf
import numpy as np

In [2]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [5]:
tf.constant(2.,dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [6]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant("Hello, World")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, World'>

In [8]:
with tf.device("cpu"):
    a = tf.constant([1])

In [9]:
with tf.device('gpu'):
    b = tf.range(4)

In [10]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [11]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [12]:
b.numpy()

array([0, 1, 2, 3], dtype=int32)

In [13]:
b.ndim

1

In [14]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
b.shape

TensorShape([4])

In [18]:
tf.rank(tf.ones([2,3,4]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [22]:
tf.is_tensor(a)

True

In [24]:
tf.is_tensor(np.arange(4))

False

In [25]:
a.dtype

tf.int32

In [27]:
a.dtype==tf.int32

True

In [30]:
a = np.arange(5)

In [31]:
a.dtype

dtype('int64')

In [32]:
aa = tf.convert_to_tensor(a)

In [33]:
aa

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [34]:
aa = tf.convert_to_tensor(a,dtype=tf.int32)

In [35]:
aa

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [36]:
tf.cast(aa,dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [37]:
aaa = tf.cast(aa,dtype=tf.double)

In [38]:
tf.cast(aaa,dtype=tf.int32)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [39]:
b = tf.constant([0,1])

In [40]:
tf.cast(b,dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [41]:
bb = tf.cast(b,dtype=bool)

In [42]:
tf.cast(bb,tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [43]:
a = tf.range(5)

In [44]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [49]:
b = tf.Variable(a,name='input_data') # Variable包装后,自动记录了梯度的信息,具有了一些求导的特性

In [50]:
b.dtype

tf.int32

In [51]:
b.name

'input_data:0'

In [52]:
b.trainable # trainable说明参数是需要梯度信息 

True

In [53]:
b.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

In [54]:
tf.is_tensor(b)

True

In [55]:
a = tf.ones([])

In [58]:
a.numpy()

1.0

In [59]:
int(a)

1