In [1]:
import tensorflow as tf

In [2]:
a = tf.linspace(-6., 6, 10)

In [3]:
a

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-6.       , -4.6666665, -3.3333333, -2.       , -0.6666665,
        0.666667 ,  2.       ,  3.333334 ,  4.666667 ,  6.       ],
      dtype=float32)>

In [4]:
tf.sigmoid(a)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247264, 0.00931591, 0.03444517, 0.11920291, 0.33924365,
       0.6607564 , 0.8807971 , 0.96555483, 0.99068403, 0.99752736],
      dtype=float32)>

In [5]:
x = tf.random.normal([1, 28, 28])

In [6]:
x = tf.sigmoid(x)

In [7]:
tf.reduce_min(x), tf.reduce_max(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.03232521>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9576025>)

In [8]:
a = tf.linspace(-2., 2, 5)

In [9]:
tf.sigmoid(a)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.11920291, 0.26894143, 0.5       , 0.7310586 , 0.8807971 ],
      dtype=float32)>

In [10]:
# y1+y2+y3+y...=1
tf.nn.softmax(a)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.01165623, 0.03168492, 0.08612854, 0.23412165, 0.6364086 ],
      dtype=float32)>

In [11]:
# 均匀分布
logits = tf.random.uniform([1, 10], minval=-2, maxval=2)

In [12]:
logits

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 0.5890517 ,  1.3227434 , -0.80312586,  0.41175985, -0.52557325,
        -0.62223625, -0.681993  , -1.3265357 ,  1.4733677 ,  0.48756552]],
      dtype=float32)>

In [13]:
prob = tf.nn.softmax(logits, axis=1)

In [15]:
tf.reduce_sum(prob, axis=1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [16]:
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [17]:
tf.tanh(a)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.9640276, -0.7615942,  0.       ,  0.7615942,  0.9640276],
      dtype=float32)>